
const STORAGE_KEY='tshirtInventoryV1';
const LOW_STOCK_THRESHOLD=2;
const state={items:{},scanAction:'retrieve',lastScanValue:null,lastScanTs:0};
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;state.items=JSON.parse(raw);}catch(e){console.error('Load error',e)}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.items));render();}catch(e){console.error('Save error',e)}}
function parseBarcode(code){if(!code)return null;const c=String(code).trim().toUpperCase();const parts=c.split('-');if(parts.length!==2)return null;const style=parts[0]==='M'?'Men':parts[0]==='W'?'Women':null;const size=parts[1];const valid=['S','M','L','XL','2XL','3XL'];if(!style||!valid.includes(size))return null;return{style,size,barcode:`${parts[0]}-${size}`}}
function ensureItem(barcode){const parsed=parseBarcode(barcode);if(!parsed)return{error:`Invalid code: ${barcode}`};if(!state.items[parsed.barcode]){state.items[parsed.barcode]={style:parsed.style,size:parsed.size,color:'Black',barcode:parsed.barcode,quantity:0,lastUpdated:new Date().toISOString()};}return{item:state.items[parsed.barcode]}}
function applyAction(barcode,action){const res=ensureItem(barcode);if(res.error){alert(res.error+'
Expected M-<size> or W-<size>, e.g., M-S, W-3XL.');return;}const it=res.item;if(action==='sub1')it.quantity=Math.max(0,it.quantity-1);if(action==='add1')it.quantity=it.quantity+1;it.lastUpdated=new Date().toISOString();save();if(action==='retrieve'){const row=document.querySelector(`[data-barcode="${it.barcode}"]`);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.classList.add('highlight');setTimeout(()=>row.classList.remove('highlight'),1200);}}}
function exportCSV(){const rows=[["style","size","color","barcode","quantity","lastUpdated"]];const all=Object.values(state.items).sort((a,b)=>{if(a.style!==b.style)return a.style.localeCompare(b.style);const order=['S','M','L','XL','2XL','3XL'];return order.indexOf(a.size)-order.indexOf(b.size);});for(const it of all){rows.push([it.style,it.size,it.color,it.barcode,String(it.quantity),it.lastUpdated]);}const csv=rows.map(r=>r.map(f=>String(f).replaceAll('"','""')).map(s=>(/[,

]/.test(s)?`"${s}"`:s)).join(',')).join('
');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');const d=new Date();const fname=`tshirt-inventory-${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}.csv`;a.href=url;a.download=fname;a.style.display='none';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);}
function render(){const body=document.getElementById('invBody');body.innerHTML='';const entries=Object.values(state.items).sort((a,b)=>{if(a.style!==b.style)return a.style.localeCompare(b.style);const order=['S','M','L','XL','2XL','3XL'];return order.indexOf(a.size)-order.indexOf(b.size)});let total=0,low=0;for(const it of entries){total+=it.quantity;const isLow=it.quantity<=LOW_STOCK_THRESHOLD;const tr=document.createElement('tr');tr.dataset.barcode=it.barcode;const tdStyle=document.createElement('td');tdStyle.textContent=it.style;tr.appendChild(tdStyle);const tdSize=document.createElement('td');tdSize.textContent=it.size;tr.appendChild(tdSize);const tdCode=document.createElement('td');const tag=document.createElement('span');tag.className='tag';tag.textContent=it.barcode;tdCode.appendChild(tag);tr.appendChild(tdCode);const tdQty=document.createElement('td');tdQty.className='qty';const qSpan=document.createElement('span');qSpan.textContent=it.quantity;if(isLow){qSpan.className='qty-low';qSpan.title='Low stock';low++;}tdQty.appendChild(qSpan);if(isLow){const tri=document.createElement('span');tri.className='tri';tri.textContent='⚠';tdQty.appendChild(tri);}tr.appendChild(tdQty);const tdControls=document.createElement('td');tdControls.className='controls';const minus=document.createElement('button');minus.className='btn mini minus';minus.textContent='−1';minus.addEventListener('click',()=>{it.quantity=Math.max(0,it.quantity-1);it.lastUpdated=new Date().toISOString();save();});const plus=document.createElement('button');plus.className='btn mini plus';plus.textContent='+1';plus.addEventListener('click',()=>{it.quantity+=1;it.lastUpdated=new Date().toISOString();save();});tdControls.appendChild(minus);tdControls.appendChild(plus);tr.appendChild(tdControls);body.appendChild(tr);}const summary=document.getElementById('summary');summary.textContent=`Total items: ${entries.length} • Total units: ${total} • Low stock (≤ ${LOW_STOCK_THRESHOLD}): ${low}`}
let codeReader;async function openScanner(){const dlg=document.getElementById('scannerDialog');const title=document.getElementById('scanTitle');const action=document.querySelector('input[name="scanAction"]:checked').value;title.textContent=`Scan — ${action==='retrieve'?'Retrieve item':action==='sub1'?'Subtract 1':'Add 1'}`;dlg.showModal();const video=document.getElementById('video');const {BrowserMultiFormatReader}=ZXing;codeReader=new BrowserMultiFormatReader();try{await codeReader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){const text=String(result.getText?result.getText():result.text);const now=Date.now();if(state.lastScanValue===text && (now-state.lastScanTs)<750) return;state.lastScanValue=text;state.lastScanTs=now;applyAction(text,action);closeScanner();}});}catch(e){console.error(e);alert('Could not access camera. Ensure permission and HTTPS.');closeScanner();}}
function closeScanner(){const dlg=document.getElementById('scannerDialog');dlg.close();try{if(codeReader){codeReader.reset();}}catch(e){}
}
load();render();
document.getElementById('exportCsvBtn').addEventListener('click', exportCSV);
document.getElementById('scanBtn').addEventListener('click', openScanner);
document.getElementById('closeScanner').addEventListener('click', closeScanner);
